myinstagram/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include(("users.urls",'users'),namespace='users')),
    path('posts/', include(("posts.urls", 'posts'), namespace='posts')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from __future__ import absolute_import

from django.conf.urls import url
from django.urls import path

from .views import *
from .rest_views import *

urlpatterns = [
    url(r'feed/$', NewsFeed.as_view(), name='feed'),
    url(r'create/$',CreatePostView.as_view(),name='add_post'),
    url(r'(?P<username>[-\w]{1,100})/(?P<slug>\d+)/$',DetailPostView.as_view(),name='view'),
    url(r'(?P<pk>\d+)/edit/$',EditPost.as_view(), name="edit_post"),
    url(r'(?P<pk>\d+)/delete/$', DeletePost.as_view(), name="delete_post"),
    path('<int:pk>/likes', LikesList, name="post_likes"),
    path('<int:pk>/comment', addComment, name="post_add_comment"),
    path('likes/api/', LikesListApi.as_view(), name="user_likes_api"),
    path('like/<int:post_id>', LikesToggle.as_view(), name="like_toggle"),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *
from .rest_views import *
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm
app_name = "users"

urlpatterns = [
    url(r'^signup/$', SignupView.as_view(), name='signup_form'),
    url(r'^login/$', LoginView.as_view(), name='login_form'),
    url(r'^(?P<username>[-\w]{1,50})/profile/$', DetailAccountView.as_view(), name='profile'),
    url(r'^logout/$', LogOutView.as_view(), name='logout_form'),
    url(r'^(?P<username>[-\w]{1,50})/users/$',ListAccountView.as_view(),name='user_list'),
    url(r'^(?P<username>[-\w]{1,50})/update/$',UpdateAccountView.as_view(),name='update'),
    url(r'^(?P<username>[-\w]{1,50})/update/password/$',change_password,name='change_password'),
    url(r'^(?P<username>[-\w]{1,50})/followers$',FollowersListView.as_view(),name='followers'),
    url(r'^(?P<username>[-\w]{1,50})/following/$',FollowingListView.as_view(),name='following'),
    url(r'^(?P<username>[-\w]{1,50})/follow/$',follow_view,name='follow'),
    url(r'^(?P<username>[-\w]{1,50})/unfollow/$',unfollow_view,name='unfollow'),
    path('users/api/<slug:slug>', SearchApi.as_view(), name="search_api"),
]


templates/accounts/account_detail.html
{% include 'base.html' with name=username  valid=True only%}
{% block content %}
<div class="container back">
        <div class="user_header">
            <img class="display_pictures" src="{{userform.profile.avatar.url}}" />
            <div class="user_data">
                <div class="container-fluid">
                    <strong><p>{{userform.username}}</p></strong>
                    <p style="float:right">
                    {% if userform.username == username %}
                        <a href="{% url 'users:update' username=username %}">
                            <button class="btn btn-primary">Update</button>
                        </a>
                    {% elif connected %}
                        <a href="{% url 'users:unfollow' username=userform.username %}">
                            <button class="btn btn-primary">Unfollow</button>
                        </a>
                    {% else  %}
                        <a href="{% url 'users:follow' username=username %}">
                            <button class="btn btn-primary">follow</button>
                        </a>
                    {% endif %}
                    </p>
                </div>
                <div class="site_details">
                    <p><strong>{{ userform.post_count }}</strong> Posts </p>
                    <p> <strong>{{ userform.followers }}</strong> <a href="{% url 'users:followers' username=userform.username %}"> Followers </a> </p>
                    <p> <strong>{{ userform.following }}</strong> <a href="{% url 'users:following' username=userform.username %}">Following</a></p>
                </div>
                <div>
                    <p>{{userform.profile.bio}}</p>
                    <a href="http://{{userform.profile.website}}">{{userform.profile.website}}</a>
                </div>
            </div>
        </div>
        <div class="container-fluid posts" >
            {% for post in userform.posts %}
                <a href="{% url 'posts:view' username=userform.username slug=post.id%}">
                <div class="post_container">
                    <img src="{{post.file.url}}" >
                </div>
                </a>
           {% endfor %}
        </div>
    </div>
{% endblock %}

templates/accounts/account_list.html
{% include 'base.html' with name=username  valid=True only%}
{% block content %}  
<center><h3>{{title}}</h3>
    <ul class="list-group list-group-flush">
        {% for user in userform %}
           <div class="card" style="width: 60rem;height:10rem;">
                <img class="img-circle" alt="Cinque Terre" style="float:left;width: 10rem;height:10rem;" src="{{user.profile.avatar.url}}" >
                <div class="card-header">
                    <p style="float:left">@<a href="{% url 'users:profile' username=user.username %}">{{ user.username }}</a></p>
                    <p style="float:right">
                    {% if user.username == username %}
                    {% elif user.is_followed %}
                        <a href="{% url 'users:unfollow' username=user.username %}" class="btn btn-success">Unfollow</a>
                    {% elif user.nothing %}
                    {% else  %}
                        <a href="{% url 'users:follow' username=user.username %}" class="btn btn-primary">Follow</a>
                    {% endif %}
                    </p><br><br>
                </div>
                <div class="card-body">
                    <center>followers: {{ user.followers }}&nbsp;&nbsp;
                    following: {{ user.following }}</center>
                </div>
           </div>
           <br>
        {% endfor %}
    </ul>
</center>
{% endblock %}

templates/accounts/add_user_profile.html
{% include 'base.html' with name=username  valid=True only%}
{% block head %}

{% endblock %}
{% block body %}
        <script>
        $(document).ready(function(){
            var imgfield = $('#customImage')[0];
            var current = $('#currentDP')[0];
            imgfield.onchange = function(){
                console.log("working");
                var reader = new FileReader();
                reader.onloadend = function(){
                    current.src =reader.result;
                };
                reader.readAsDataURL(imgfield.files[0])
            }
        })
    </script>
        <form method="post" enctype="multipart/form-data"  >
            {% csrf_token %}
            <table class="table">
                <tr class="fieldwrapper">
                    <td><label for="currentDP" style="width:50px;height:50px;">Cureent DP</label></td>
                    <td><img name="currentDP" id="currentDP" src="{{profiledetails.avatar.url}}"/></td>
                </tr>
                <tr class="fieldwrapper">
                    <td>{{ profileform.avatar.label_tag }}</td>
                    <td>{{ profileform.avatar }}</td>
                </tr>
                <tr class="fieldwrapper">
                        <td>{{profileform.bio.label_tag}}</td>
                        <td>{{profileform.bio}}</td>
                    </tr>
                    <tr class="fieldwrapper">
                        <td>{{profileform.website.label_tag}}</td>
                        <td>{{profileform.website}}</td>
                </tr>
            </table>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>

{% endblock %}

templates/accounts/login_form.html
{% include 'base.html' %}
{% block head %}
    <style>
        td{
            padding-bottom:10px;
        }
    </style>
{% endblock %}
{% block body %}
    <center>
            <form method="post">
                {% csrf_token %}
                <table class="table">
                <tr class="fieldwrapper">
                    <td>{{ loginform.username.label_tag }}</td>
                    <td>{{ loginform.username }}</td>
                </tr>
                <tr class="fieldwrapper">
                    <td>{{ loginform.password.label_tag }}</td>
                    <td>{{ loginform.password }}</td>
                </tr>
                </table>
                <button type="submit" class="btn btn-success">Log In</button>

            </form>
    </center>
</div>
</body>
</html>
{% endblock %}

templates/accounts/signup_form.html
{% include 'base.html' %}
{% block head %}
    <style>
        td{
            padding-bottom:10px;
        }
    </style>
{% endblock %}
{% block body %}
    <center>
            <form method="post">
                {% csrf_token %}
                <table class="table">
                <tr class="fieldwrapper">
                    <td>{{ userform.username.label_tag }}</td>
                    <td>{{ userform.username }}</td>
                </tr>
                <tr class="fieldwrapper">
                    <td>{{ userform.first_name.label_tag }}</td>
                    <td>{{ userform.first_name }}</td>
                </tr>
                <tr class="fieldwrapper">
                    <td>{{ userform.email.label_tag }}</td>
                    <td>{{ userform.email }}</td>
                </tr>
                <tr class="fieldwrapper">
                    <td>{{ userform.password.label_tag }}</td>
                    <td> {{ userform.password }}</td>
                </tr>
                <tr class="fieldwrapper">
                    <td >{{ userform.confirm_password.label_tag }}</td>
                    <td>{{ userform.confirm_password }}</td>
                </tr>
                </table>
                <button type="submit" class="btn btn-success">Sign up</button>

            </form>

    </center>

{% endblock %}