myinstagram/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include(("users.urls",'users'),namespace='users')),
    path('posts/', include(("posts.urls", 'posts'), namespace='posts')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from __future__ import absolute_import

from django.conf.urls import url
from django.urls import path

from .views import *
from .rest_views import *

urlpatterns = [
    url(r'feed/$', NewsFeed.as_view(), name='feed'),
    url(r'create/$',CreatePostView.as_view(),name='add_post'),
    url(r'(?P<username>[-\w]{1,100})/(?P<slug>\d+)/$',DetailPostView.as_view(),name='view'),
    url(r'(?P<pk>\d+)/edit/$',EditPost.as_view(), name="edit_post"),
    url(r'(?P<pk>\d+)/delete/$', DeletePost.as_view(), name="delete_post"),
    path('<int:pk>/likes', LikesList, name="post_likes"),
    path('<int:pk>/comment', addComment, name="post_add_comment"),
    path('likes/api/', LikesListApi.as_view(), name="user_likes_api"),
    path('like/<int:post_id>', LikesToggle.as_view(), name="like_toggle"),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *
from .rest_views import *
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm
app_name = "users"

urlpatterns = [
    url(r'^signup/$', SignupView.as_view(), name='signup_form'),
    url(r'^login/$', LoginView.as_view(), name='login_form'),
    url(r'^(?P<username>[-\w]{1,50})/profile/$', DetailAccountView.as_view(), name='profile'),
    url(r'^logout/$', LogOutView.as_view(), name='logout_form'),
    url(r'^(?P<username>[-\w]{1,50})/users/$',ListAccountView.as_view(),name='user_list'),
    url(r'^(?P<username>[-\w]{1,50})/update/$',UpdateAccountView.as_view(),name='update'),
    url(r'^(?P<username>[-\w]{1,50})/update/password/$',change_password,name='change_password'),
    url(r'^(?P<username>[-\w]{1,50})/followers$',FollowersListView.as_view(),name='followers'),
    url(r'^(?P<username>[-\w]{1,50})/following/$',FollowingListView.as_view(),name='following'),
    url(r'^(?P<username>[-\w]{1,50})/follow/$',follow_view,name='follow'),
    url(r'^(?P<username>[-\w]{1,50})/unfollow/$',unfollow_view,name='unfollow'),
    path('users/api/<slug:slug>', SearchApi.as_view(), name="search_api"),
]


templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Instagram</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script>
            var hasScrolled=false;
            $(document).ready(function(){
                $("textarea").attr("rows",1);
                var search_results = $("#search-results");
                search_results.hide();
                var search_bar = $("#search-bar");
                search_bar.focus(function () {
                    search_results.show()
                });
                $('html').click(function () {
                    search_results.empty();
                    search_results.hide();
                })
            });
            function search_bar(slug) {
                var search_results = $("#search-results");
                if(slug.length>0){
                    search_results.empty();
                    var xhttp = new XMLHttpRequest();
                    xhttp.onreadystatechange = function () {
                        if (this.readyState === 4 && this.status === 200) {
                            $('#search-results').show();
                            var json = JSON.parse(this.responseText);
                            json.forEach(function(item){
                               var temp = $("<tr><td class='pic'><img class='thumbnail' src="+item['avatar']+"/></td><td><a href='/users/"+item.user_id.username+"/profile'>"+item.user_id.username+"</a></td></tr>");
                               search_results.append(temp);
                            });
                        }
                    };
                    xhttp.open("GET" ,"/users/users/api/"+slug,true);
                    xhttp.send();
                }else{
                    search_results.empty()
                }
            }
            $(window).scroll(function () {
                var scroll = $(this).scrollTop();
                if( scroll > 250){
                    $('#header_text').hide();
                    $('nav').addClass('shrink')
                }else{
                    $('#header_text').show();
                    $('nav').removeClass('shrink')
                    //if(scroll < 10) $('#header').animate({padding:'1% 15%'},100);
                }
            });
            setInterval(function () {
                if (hasScrolled){
    
                }
            },250)
        </script>
    {% block head %}

    {% endblock %}
</head>
<body class="back">
<nav  id="header" class="navbar navbar-default navbar-fixed-top front">
  <div class="container-fluid">

        <div class="navbar-header" style="float:left;" >
            <a href="{% url 'posts:feed' %}">
            <img id="header_logo" class="navbar-brand" src="{% static 'Instagram-header-logo.png'%}"/>
            <img id="header_text" class="navbar-brand" src="{% static 'Instagram-logo-png-text.png'%}"/>
            </a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>

     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
         {% if user.is_authenticated or valid %}
            <ul class="nav navbar-nav mr-auto">
                <li class="nav-item"><a href="{% url 'users:user_list' username=name %}">People</a></li>
                <li class="nav-item"><a href="{% url 'posts:add_post' %}">Upload</a></li>
            </ul>
           <div class="navbar-nav" style="width:200px;display: inline-block;" id="search_container">
                <input type="text"  onkeyup="search_bar(this.value)"  id="search-bar" placeholder=" Search..."/>
               <div id="search-results-container">
                   <table id="search-results" ></table>
               </div>
           </div>
        {% endif %}

        <ul class="nav navbar-nav mr-auto navbar-right">
            {% if user.is_authenticated  or valid%}
                <li class="nav-item"><a href="{% url 'users:profile' username=name %}">Profile</a></li>
                <li class="nav-item"><a href="{% url 'users:logout_form' %}">Log Out</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'users:login_form' %}">Log In</a></li>
                <li class="nav-item"><a href="{% url 'users:signup_form' %}">Sign Up</a></li>
            {% endif %}
        </ul>
     </div>
   </div>
 </nav>
    <div class="container back">

templates/post_details.html
{% extends "base.html" %}

{% block body %}
    <script>
        var hasLiked = "{{ hasLiked }}";
        var likedClass = "glyphicon-heart";
        var unlikedClass = "glyphicon-heart-empty";


    $(document).ready(function(){
        var element = $('.likes')[0];
        if(hasLiked === "1"){
            element.classList.remove(unlikedClass);
            element.classList.add(likedClass,"red");
        }else{
            //element.classList.remove(likedClass,"red");
            element.classList.add(unlikedClass);
        }
    });
    var like_toggle = function (element) {
            var xhttp =  new XMLHttpRequest();
            xhttp.onreadystatechange = function (){
                if(this.readyState === 4 && this.status === 200){
                    var response = this.responseText.split(',');
                    if(response[0] === "1"){
                        element.classList.remove(unlikedClass);
                        element.classList.add(likedClass,"red");
                    }else{
                        element.classList.remove(likedClass,"red");
                        element.classList.add(unlikedClass);
                    }
                    element.parentElement.getElementsByClassName('likes_count')[0].innerHTML = response[1];
                }
            };
            xhttp.open("GET","like/"+element.getAttribute("post_id"),true);
            xhttp.send()
        };
        var addComment =function (event) {
            if(event.key === "Enter"){
                var comment =$('#comment_text')[0];
                $.ajax({
                    type : "POST",
                    url : "{% url 'posts:post_add_comment' post.id %}",
                    data : {
                        "comment": comment.value
                        //"csrfmiddlewaretoken": csrf
                    },
                    success : function (data) {
                           var response = data.split(":");
                           console.log(response);
                            var comment = $("<div class=\"comment\">\n<p><strong>"+response[0]+" </strong> "+response[1]+"</p>\n</div>");
                            $("#comments_container").append(comment);
                            $("#comment_text")[0].value=""
                    },
                    failure : function (data) {
                        console.log("failure");
                        console.log(data);
                    }
                })
            }
        };
        function likeDoubleClick(id) {
            console.log("working");
            var xhttp =  new XMLHttpRequest();
            var element = $('#'+id)[0];
            xhttp.onreadystatechange = function (){
                if(this.readyState === 4 && this.status === 200){
                    var response = this.responseText.split(',');
                    if(response[0] === "1"){
                        element.classList.remove(unlikedClass);
                        element.classList.add(likedClass,"red");
                    }else{
                        element.classList.remove(likedClass,"red");
                        element.classList.add(unlikedClass);
                    }
                    element.parentElement.getElementsByClassName('likes_count')[0].innerHTML = response[1];
                }
            };
            xhttp.open("GET","like/"+id,true);
            xhttp.send()
        }
    </script>

    <div class="posted_data">
        {% if user.id == post.uploader.id %}
            <nav >
                <a href="{% url 'posts:delete_post' post.id %}" class="controller"><button class="btn btn-danger pull-right">Delete</button></a>
                <a href="{% url 'posts:edit_post' post.id %}" class="controller"><button class="btn btn-primary pull-right">Edit</button></a>
            </nav>
        {% endif %}
        <div class="posted_picture">
            <img ondblclick="likeDoubleClick({{ post.id }})" src="{{ post.image.url }}"/>
        </div>
        <div class="post_related_data" >
            <div class="user_details">
                <img  class="display_pictures" src="{{ profile.display_picture.url }}" alt="display picture" width="100px"/>
                <p><strong>{{ profile.user.username }}</strong></p> <p class="status">{{ post.status }}</p>
            </div>

            <br>
            <div class="likes_comments">
                <div id="comments_container">
                    {% for comment in comments %}
                        <div class="comment">
                        <p><strong> {{ comment.comment }} </strong> {{ comment.comment }}</p>
                        </div>
                    {% endfor %}
                </div>

            </div>
            <div class="functionalities">
                <p><span onclick="like_toggle(this)" id="{{ post.id }}" class="likes glyphicon" post_id="{{ post.id }}"></span> <a href="{% url 'posts:post_likes' post.id %}"><span class="likes_count" >{{ likes.count }}</span> likes</a></p>
                    <div id="add_comment">
                        <input type="Text" name="comment" autocomplete="off" onkeypress="addComment(event)" id="comment_text" placeholder="Add a comment..."/><br>
                    </div>
            </div>

        </div>

    </div>
{% endblock %}